### ISSUE TITLE
Docker unable to find /app/noisy.py

### ISSUE THREAD

**Issue by Shadow00Caster** [madereddy/noisy#10]
Using latest docker image as of today and am getting: `python: can't open file '/app/noisy.py': [Errno 2] No such file or directory`

Container is deployed with compose from readme:
```
version: "2"
services:
  noisy:
    image: madereddy/noisy:latest
    container_name: noisy
    restart: always
```
